name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - production

jobs:
  deploy-staging:
    if: github.ref == 'refs/heads/main' || github.event.inputs.environment == 'staging'
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push backend image
        run: |
          cd backend
          docker build -t ${{ secrets.REGISTRY_URL }}/metron-audit-backend:${{ github.sha }} .
          docker push ${{ secrets.REGISTRY_URL }}/metron-audit-backend:${{ github.sha }}

      - name: Build and push frontend image
        run: |
          cd frontend
          docker build -t ${{ secrets.REGISTRY_URL }}/metron-audit-frontend:${{ github.sha }} .
          docker push ${{ secrets.REGISTRY_URL }}/metron-audit-frontend:${{ github.sha }}

      - name: Deploy to staging
        run: |
          echo "Deploying to staging environment..."
          # Add your deployment commands here
          # Example: kubectl apply -f k8s/staging/

      - name: Upload deployment artifacts
        uses: actions/upload-artifact@v4
        with:
          name: staging-deployment
          path: |
            backend/
            frontend/

  deploy-production:
    if: github.event.inputs.environment == 'production'
    runs-on: ubuntu-latest
    environment: production
    needs: deploy-staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push backend image
        run: |
          cd backend
          docker build -t ${{ secrets.REGISTRY_URL }}/metron-audit-backend:prod-${{ github.sha }} .
          docker push ${{ secrets.REGISTRY_URL }}/metron-audit-backend:prod-${{ github.sha }}

      - name: Build and push frontend image
        run: |
          cd frontend
          docker build -t ${{ secrets.REGISTRY_URL }}/metron-audit-frontend:prod-${{ github.sha }} .
          docker push ${{ secrets.REGISTRY_URL }}/metron-audit-frontend:prod-${{ github.sha }}

      - name: Deploy to production
        run: |
          echo "Deploying to production environment..."
          # Add your deployment commands here
          # Example: kubectl apply -f k8s/production/

      - name: Upload deployment artifacts
        uses: actions/upload-artifact@v4
        with:
          name: production-deployment
          path: |
            backend/
            frontend/
